import { CarPart } from "../interfaces/car-part.interface";

export const CAR_PARTS = {
  PARAFANGO_AD: "Parafango-ad",
  PORTA_AD: "Porta-ad",
  PORTA_PD: "Porta-pd",
  PARAFANGO_PD: "Parafango-pd",
  COFANO: "Cofano",
  TETTO: "Tetto",
  PIAZONE_D: "Pianzone-d",
  PIAZONE_S: "Pianzone-s",
  SPORTELLO_S: "Sportello-s",
  SPORTELLO_I: "Sportello-i",
  PARAFANGO_AS: "Parafango-as",
  PORTA_AS: "Porta-as",
  PORTA_PS: "Porta-ps",
  PARAFANGO_PS: "Parafango-ps",
};

export const initialCarParts: CarPart[] = [
  {
    name: CAR_PARTS.PARAFANGO_AD,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PORTA_AD,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PORTA_PD,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PARAFANGO_PD,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.COFANO,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.TETTO,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PIAZONE_D,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PIAZONE_S,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.SPORTELLO_S,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.SPORTELLO_I,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PARAFANGO_AS,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PORTA_AS,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PORTA_PS,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
  {
    name: CAR_PARTS.PARAFANGO_PS,
    isAluminum: true,
    shouldPaint: true,
    shouldReplace: true,
    shouldGlue: true,
    smallSmash: "",
    smash: "",
  },
];
